language: php

sudo: true

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
- composer install
- travis_retry composer self-update
- travis_retry composer update --no-interaction --prefer-dist

script:
- vendor/bin/phpunit
